### ISSUE TITLE
Generating longer tracks

### ISSUE THREAD

**Issue by samim23** [hugofloresgarcia/vampnet#5]
Hi Hugo, thank you so much for vampnet, really fantastic stuff!

I'm trying to generate longer songs than the current 10s limit. I have tried adjusting the following in the `interface.yml:`

```
Interface.coarse_chunk_size_s: 30
Interface.coarse2fine_chunk_size_s: 3
```

But when ever it's longer than 10s, somehow it only generates garbled weirdness. 
Is there any other settings i need to adjust which i am overseeing?

Thank you in advance!
samim

**Comment by hugofloresgarcia** [comment]
Hi samim!

Unfortunately, VampNet can't generate songs loner than 10s. This is due to the fact that VampNet uses relative attention, and any tokens beyond 10s will consist of, garbled weirdness. 

My suggestion would be to set `coarse_chunk_size_s` to 10, generate 10s of audio, then generate again using the last 2-5s   of the output as a prefix prompt for the next round of generation, and so forth. 

Let me know if this works!

**Comment by samim23** [comment]
Thanks for the suggestion! I have tried a variation of the suggested technique: Generating 10s, then taking the last 3s of that and feeding it as prefix to the next generation round, and so forth. While this sort of works, the problem i ran into is that since the prefix is always audible, when stitching together multiple generated files it results in the prefix part being audible twice. And i simply chop off the prefix after generation, i get an overall mix that is not smoothly continuous. Currently exploring different venues to achieve the longer track generation with vamp, any ideas most welcome @hugofloresgarcia !
